name: Deploy AST Builder

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: Use Node.JS
      uses: actions/setup-node@v4
      with:
        node-version: '24.12'
    
    - name: Install Dependencies
      run: npm install
    - name: create .env.production
      run : |
         echo "VITE_API_URL=https://ast.camberit.co.nz" >> .env.production
        
    - name: Build
      run: npm run build

    - name: Copy front end Build
      uses: appleboy/scp-action@v0.1.4
      with:
          host: ast.camberit.co.nz
          username: azureuser
          key: ${{ secrets.AST_SSH}}
          source: "frontend/dist/**"
          target: "/var/www/html/ast.camberit.co.nz"
          strip_components: 2
          
    - name: env server
      run : |
        echo "PORT=3001" >> backend/.env.production
        echo "FRONTEND_URL=https://ast.camberit.co.nz" >> backend/.env.production
        echo "SESSION_SECRET=CHANGE_THIS_TO_A_SECURE_RANDOM_STRING" >> backend/.env.production
        echo "NODE_ENV=production" >> backend/.env.production
        echo "LOG_LEVEL=debug" >> backend/.env.production
      
    
    
    - name: Copy Server
      uses: appleboy/scp-action@v0.1.4
      with:
          host: ast.camberit.co.nz
          username: azureuser
          key: ${{ secrets.AST_SSH}}
          source: "backend/**"
          target: "~/astserver"
          stip_components: 1
      
     
      
    
