name: Deploy AST Builder

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: Use Node.JS
      uses: actions/setup-node@v4
      with:
        node-version: '24.12'
    
    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Copy Build
      uses: appleboy/scp-action@v0.1.4
      with:
          host: ast.frapper.co.nz
          username: azureuser
          key: ${{ secrets.FISH_SSH}}
          source: "dist"
          target: "/var/www/html/ast.frapper.co.nz"
          strip_components: 1
      
    
